### ISSUE TITLE
ERROR:neo4j:Unable to retrieve routing information

### ISSUE THREAD

**Issue by phillipshaong** [neo4j-examples/movies-python-bolt#60] opened 2022-01-13 20:50 UTC
I followed the instruction on the README.md.

The Neo4j server works just fine, using the Desktop application and browser, I can see the movies data. 

When I deploy the FastAPI server, it gives me this error. 

```
File "/Users/phillipn/Desktop/movies-python-bolt/movies_async.py", line 78, in get_graph
    results = await db.read_transaction(work)
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/work/session.py", line 407, in read_transaction
    return await self._run_transaction(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/work/session.py", line 360, in _run_transaction
    raise errors[-1]
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/work/session.py", line 327, in _run_transaction
    await self._open_transaction(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/work/session.py", line 257, in _open_transaction
    await self._connect(access_mode=access_mode)
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/work/session.py", line 109, in _connect
    await super()._connect(access_mode)
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/work/workspace.py", line 80, in _connect
    self._connection = await self._pool.acquire(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/io/_pool.py", line 657, in acquire
    await self.ensure_routing_table_is_fresh(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/io/_pool.py", line 602, in ensure_routing_table_is_fresh
    await self.update_routing_table(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_async/io/_pool.py", line 570, in update_routing_table
    raise ServiceUnavailable("Unable to retrieve routing information")
neo4j.exceptions.ServiceUnavailable: Unable to retrieve routing information
```

The same thing happens with the Flask server:

```
File "/Users/phillipn/Desktop/movies-python-bolt/movies.py", line 120, in get_search
    results = db.read_transaction(work, q)
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 407, in read_transaction
    return self._run_transaction(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 360, in _run_transaction
    raise errors[-1]
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 327, in _run_transaction
    self._open_transaction(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 257, in _open_transaction
    self._connect(access_mode=access_mode)
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/work/session.py", line 109, in _connect
    super()._connect(access_mode)
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/work/workspace.py", line 80, in _connect
    self._connection = self._pool.acquire(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 657, in acquire
    self.ensure_routing_table_is_fresh(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 602, in ensure_routing_table_is_fresh
    self.update_routing_table(
  File "/Users/phillipn/neo4j-movies/lib/python3.10/site-packages/neo4j/_sync/io/_pool.py", line 570, in update_routing_table
    raise ServiceUnavailable("Unable to retrieve routing information")
neo4j.exceptions.ServiceUnavailable: Unable to retrieve routing information
```

I'm not sure what it could be. Thanks!

Environment:
Python 3.10.1

**Comment by robsdedude** [comment] 2022-01-17 10:45
Hi and thanks for reaching out. The README is a little confusing and we are working on updating it. If you just start the demo application without any application relevant environment variables set (they are all listed at the end of the README), the application will connect to a demo database hosted by us for you, so you don't even have to start a local database. Could you please try to connect to the database via https://demo.neo4jlabs.com:7473/browser/?dbms=neo4j://movies@demo.neo4jlabs.com&db=movies ?

**Comment by robsdedude** [comment] 2022-01-17 11:04
I'll close this issue as it's not a bug in the example code. Please feel free to still keep communicating here!

**Closed by robsdedude** 2022-01-17 11:04 UTC

**Comment by fabianB30** [comment] 2024-05-01 04:18
Hello, im having the same issue while using the example code as is

**Comment by robsdedude** [comment] 2024-05-02 10:03
@fabianB30 can you reach the DBMS through browser (as I've linked above)? Have you set any of the environment variables as listed in the README? (As written above, if you don't, things should work out of the box assuming your PC can connect to the server).
